swagger: '2.0'
info:
  description: 'Este é um serviço disponibilizado pela AMA que fornece interoperabilidade com o Single Digital Gateway (SDG) da Comissão Europeia. Esta api deve ser chamada antes de invocar outras apis da SDG de maneira a obter o uniqueId que terá de ser fornecida nessas invocações. Adicionalmente, esta api tem uma operação que verifica a validade de um id existente.'
  version: 1.0.0
  title: "SDG - uniqueId"
  termsOfService: 'https://www.ama.gov.pt/web/agencia-para-a-modernizacao-administrativa/politica-de-privacidade'
  contact:
    email: "apiteam@ama.pt"
host: "esb.ama.lan"


schemes:
  - "https"
  - "http"
paths:
  /uniqueId:
    get:
      tags:
      - "obter id"
      summary: "Obter um unique id para uso nas apis da SDG."
      description: "Esta operação tem como objetivo disponibilzar um id único que poderá ser utilizado ao invocar outras apis da SDG."
      produces:
      - "application/json"
      responses:
        '200':
          description: "Operação realizada com sucesso"
          schema:
            $ref: '#/definitions/ApiResponseSuccess'
        '500':
          description: "Erro"
          schema:
            $ref: '#/definitions/ApiResponseError'
  /uniqueId/{id}:
    get:
      tags:
      - "validar id"
      summary: "Validar um id."
      description: "Esta operação tem como objetivo validar um id, devolvendo válido ou inválido"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id a ser validado"
        required: true
        type: "string"
      responses:
        '200':
          description: "Operação realizada com sucesso"
          schema:
            $ref: '#/definitions/ValidateResponseSuccess'
        '500':
          description: "Erro"
          schema:
            $ref: '#/definitions/ApiResponseError'
definitions:
  ApiResponseSuccess:
    type: "object"
    properties:
      unique-id:
        type: "string"
        example: "b4bc555f-3fbf-4757-b57c-c58d4e7f24fd"

  ValidateResponseSuccess:
    type: "object"
    properties:
      unique-id:
        type: "string"
        example: "valid"


  ApiResponseError:
    type: "object"
    properties:
      ERROR_CODE:
        type: "integer"
        format: "int32"
      errorDescription:
        type: "string"
        example: ""
      STATUS_CODE:
        type: "integer"
        example: 500
      message:
        type: "string"
        example: ""
      ERROR_MESSAGE:
        type: "string"
        example: ""
      ERROR_DETAIL:
        type: "string"
        example: ""
      ERROR_EXCEPTION:
        type: "string"
        example: ""
externalDocs:
  description: "Encontre mais sobre o serviços da AMA em"
  url: 'http://www.ama.gov.pt'
