//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Somador.IAPSomadorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAPSomadorService.TutorialSomadorSoap")]
    public interface TutorialSomadorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Somador", ReplyAction="*")]
        void Somador(int numero1, int numero2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TutorialSomadorSoapChannel : Somador.IAPSomadorService.TutorialSomadorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TutorialSomadorSoapClient : System.ServiceModel.ClientBase<Somador.IAPSomadorService.TutorialSomadorSoap>, Somador.IAPSomadorService.TutorialSomadorSoap {
        
        public TutorialSomadorSoapClient() {
        }
        
        public TutorialSomadorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TutorialSomadorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TutorialSomadorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TutorialSomadorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Somador(int numero1, int numero2) {
            base.Channel.Somador(numero1, numero2);
        }
    }
}
